### ISSUE TITLE
Add easy way to get best-fit model(s) after an optimization/sample.

### ISSUE THREAD

**Issue by zkbt** [catrionamurray/chromatic_fitting#12]
@Pat-Wachiraphan and @catrionamurray  have been talking about ways of retrieving model flux arrays associated with a fitted model. Ideally, it would be nice to to have a function that creates a new `RainbowWithModel` object that contains the original data as well some new fluxlike arrays to express the models. For example, if there's been a fit including a TransitModel and a SystematicsModel, you might have:
- `model` = the noiseless multiwavelength model, including all components
- `transit_model` = the noiseless multiwavelength transit model, including all components
- `systematics_model` = the noiseless multiwavelength systematics model, including all components

With that `RainbowWithModel` object defined, we could then do something like:
```python
r.imshow_with_models()
```
![image](https://user-images.githubusercontent.com/4691081/178361023-9f52552b-ac2c-46f1-833d-714a8514eb6b.png)
```python
r.bin(R=10).animate_with_models('test.gif', orientation='horizontal')
```
![test](https://user-images.githubusercontent.com/4691081/178361074-1790152f-a2a9-4310-98ec-64148d467475.gif)
Just for a convenient way to see everything at once.

**Comment by zkbt** [comment]
Ha! I had opened an issue to add a function to help with this, but apparently I had already written it. You can do 
```python
rainbow.attach_model(model=..., transit_model=..., systematics_model=...)
``` 
to get a new `RainbowWithModel`. 

Please let me know if I can help with this any more! It seems like using `Deterministic` is the code-easiest way to make this happen.

**Comment by catrionamurray** [comment]
Just as an aside, I think `animate_with_models` doesn't work with Python < 3.9 - I got this error and the | operator for dictionaries is introduced I believe in 3.9:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [25], in <cell line: 1>()
----> 1 r_with_model.animate_with_models('test.gif', orientation='horizontal')

File ~/opt/anaconda3/envs/chromaticfitting/lib/python3.8/site-packages/chromatic/rainbows/visualizations/models/plot_one_wavelength_with_models.py:333, in animate_with_models(self, filename, fps, bitrate, dpi, **kw)
    324 def animate_with_models(
    325     self,
    326     filename="animated-lightcurves-with-models.html",
   (...)
    330     **kw,
    331 ):
--> 333     self.plot_one_wavelength_with_models(0, animation=False, **kw)
    335     # initialize the animator
    336     writer, displayer = _get_animation_writer_and_displayer(
    337         filename=filename, fps=fps, bitrate=-1
    338     )

File ~/opt/anaconda3/envs/chromaticfitting/lib/python3.8/site-packages/chromatic/rainbows/visualizations/models/plot_one_wavelength_with_models.py:219, in plot_one_wavelength_with_models(self, i_wavelength, models, vlimits_data, vspan_residuals, panelsize, orientation, errorbar, text, data_errorbarkw, model_plotkw, wavelength_textkw, cmap, vmin, vmax, w_unit, t_unit, label, label_textkw, animation, minimum_acceptable_ok, **kw)
    215 xlabel = f"Time ({t_unit.to_string('latex_inline')})"
    217 # set defaults for the model line plots
    218 plotkw = (
--> 219     dict(marker=None, linewidth=1, zorder=1, color=color, alpha=0.5) | model_plotkw
    220 )
    222 # set default for the data errorbar plots
    223 default_markersize = plt.matplotlib.rcParams["lines.markersize"]

TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

```

**Comment by zkbt** [comment]
Oh, blerg. Thanks for that catch; I'll go through and fix those. As far as I know, that's the only feature that needs python 3.9, so we might as well fix it to still allow easier versions.

**Comment by catrionamurray** [comment]
Done! There's now animate_with_models, plot_lightcurves and imshow_with_models in CombinedModel

**Comment by catrionamurray** [comment]
![test](https://user-images.githubusercontent.com/34891147/178609533-95b8e71b-0e51-44bd-9a96-2dd9832524ad.gif)
![lightcurves_with_models](https://user-images.githubusercontent.com/34891147/178609874-afd31319-5712-4dfc-808b-516814fb7220.png)
![imshow_with_models](https://user-images.githubusercontent.com/34891147/178609876-c7327fc7-7f3b-4c93-9923-8a854b4fa249.png)

**Comment by catrionamurray** [comment]
closing this as `.get_model()` in the newer versions of chromatic_fitting does this job!
