### ISSUE TITLE
Does the user need to see `.initialize_empty_model()`?

### ISSUE THREAD

**Issue by zkbt** [catrionamurray/chromatic_fitting#14]
Playing with the combing ;-) models tutorial, I'm curious if the user needs to see the `.initialize_empty_model()` method directly, or if it's something that could just be called in the background when needed, for example if a model object is trying to `setup_lightcurves` and sees that a `pymc3_model` hasn't been defined yet. 

If it's not necessary for most users, removing it might make for a tidier user interface?

**Comment by catrionamurray** [comment]
Agreed, this will be done in the __init__ stage in the next update!
