### ISSUE TITLE
Add trapezoidal transit model. 

### ISSUE THREAD

**Issue by zkbt** [catrionamurray/chromatic_fitting#18]
As we just discussed, it might be nice to add a simple trapezoidal transit model to `chromatic_fitting.` Following https://arxiv.org/abs/1001.2010, the parameters of this might be something like the out-of-transit baseline flux, the transit depth, the total transit duration, and the ingress/egress time. This would be quick to calculate and conceptually simple. 

Possible applications would include:
- tests, since it should be much faster than any limb-darkened code and would have no complicated dependencies, so it'd be a way to play (albeit approximately) with the transit fitting problem
- pedagogy, since the parameters being fitted would be the ones that are most directly linked to what we actually see in the observations (as in, it's basically a model we could draw by hand through the data and measure with a ruler). I think it could make for some really nice tutorials, for example showing how the uncertainty on the depth changes with noise, cadence, transit duration
- science, since for some low-S/N datasets, more detailed modeling might be overkill. For example, for a shallow eclipse, a trapezoidal model might work just as well as `starry`, with much less computational cost

**Comment by zkbt** [comment]
I realized I wrote one of these along time ago for a class [here](https://github.com/zkbt/henrietta/blob/653d798b241ad5591b704967a0413a2457a4e734/henrietta/fitting.py#L20). I don't know how this gets most efficiently translated to jax/pymc-ish, but maybe it's a helpful starting place?

**Comment by catrionamurray** [comment]
Added trapezoid model in commit https://github.com/catrionamurray/chromatic_fitting/commit/9fd4e44487cf7210623ff37aae077f43851ebf34
