### ISSUE TITLE
Add a linear systematics model.

### ISSUE THREAD

**Issue by zkbt** [catrionamurray/chromatic_fitting#4]
In `chromatic`, you can make a cartoonish systematics-ridden dataset with 
```
(SimulatedRainbow()
 .inject_transit()
 .inject_systematics(amplitude=0.002)
 .inject_noise(signal_to_noise=500)
 .imshow())
```
It'd be good to have a model to match what goes into that systematics simulation. The final `model` used to generate the flux is `planet_model`*`systematics_model`, where `planet_model` should be 1 out of transit and `systematics_model` should wobble close to 1. 

The systematics injected (with the default inputs) are `S = a*x + b*y + c*time +d*background`, where some of those are `timelike` (x, y, time) and some are `fluxlike` (background). Those inputs are all stored in the appropriate dictionaries, so it should be possible to perfectly reconstruct the model and to fit for the coefficients [a, b, c, d].

![image](https://user-images.githubusercontent.com/4691081/174393917-6022aea8-b072-4c1e-a826-3dabd7c96f28.png)

![image](https://user-images.githubusercontent.com/4691081/174393960-963f2087-41f5-4ba6-9ea7-422dc5a5326b.png)

I think that's a basic model that may really come in handy for some of the JWST datasets! It'd be similar to `PolynomialModel` but would need to specify which inputs should be uses as the independent variable(s) instead of time. Starting with something linear might be easiest to code up, with just 1 parameter per independent variable?

**Comment by catrionamurray** [comment]
This is so cool! Could we just use the PolynomialModel but take an extra argument for `setup_lightcurves` that by default is time but could be any series with same length as time?
`b_x.setup_lightcurves(series=self.data.x)`
`b_t.setup_lightcurves()`
`b_bkg.setup_lightcurves(series=self.data.background)`

**Comment by catrionamurray** [comment]
So in my head taking your systematics model: 
`S = a*x + b*y + c*time +d*background`
the CombinedModel would be:
`CM = b_x + b_y + b_t + b_bkg + TransitModel`
or 
`CM.attach_models{'x':b_x, 'y':b_y, 'bkg':b_bkg, 'transit':TransitModel}` as it currently is in the code

**Comment by catrionamurray** [comment]
![systematics](https://user-images.githubusercontent.com/34891147/174888344-a09aa311-04fb-4b0d-a2c9-a372ae1fbf46.png)

**Comment by catrionamurray** [comment]
Working for this test case in [systematics_model](https://github.com/catrionamurray/chromatic_fitting/tree/systematics_model) branch - will try with more wavelengths

**Comment by catrionamurray** [comment]
Not actually working - it converges, but the solution seems to be wrong - something to do with my priors

**Comment by zkbt** [comment]
I think I didn't actually get around to storing the randomly generated coefficients anywhere when `inject_systematics` are run. Would it help to store those coefficients, so you know exactly what the model is?

**Comment by catrionamurray** [comment]
That would be very helpful, thanks!

**Comment by zkbt** [comment]
OK, version `0.2.2` (which is now the current version on `develop`) should allow 
```python
from chromatic import *
s = SimulatedRainbow().inject_systematics()
print(s.metadata['systematics_equation'])
print()
for k, v in s.metadata['systematics_components'].items():
    print(f'{k:>20} = {repr(v)}')
```
which gives something like
```
f = 1
  + c_x*(x - offset_x)/sigma_x
  + c_y*(y - offset_y)/sigma_y
  + c_time*(time - offset_time)/sigma_time
  + c_background*(background - offset_background)/sigma_background

            linear_x = 'c_x*(x - offset_x)/sigma_x'
                 c_x = -0.0015579893057010063
            offset_x = 0
             sigma_x = 1
            linear_y = 'c_y*(y - offset_y)/sigma_y'
                 c_y = -0.0013126089352345203
            offset_y = 0
             sigma_y = 1
         linear_time = 'c_time*(time - offset_time)/sigma_time'
              c_time = -0.0028084885447004597
         offset_time = <Quantity -0.00069444 d>
          sigma_time = <Quantity 0.06013932 d>
   linear_background = 'c_background*(background - offset_background)/sigma_background'
        c_background = 0.0024764780044786543
   offset_background = 0
    sigma_background = 1
```
And to be clear, `.inject_transit().inject_systematics()` will inject a transit model that has a baseline of exactly 1, and then *multiply* the flux array for that transit model by the systematics model, so the final flux is `flux = planet_model*systematics_model`.
